language: r

r:
  - release
#  - oldrel
#  - devel

# cache: packages

sudo: required

dist: trusty

warnings_are_errors: true

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
